routes/web.php
<?php

use App\Http\Controllers\CategoryController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\PermissionController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::resource('/admin/users', UserController::class)
    ->middleware('can:manage-users');

Route::prefix('admin')->middleware('auth')->group(function () {
    //--------------------------------------------Role------------------------------------------//
    Route::prefix('/role')->name('roles.')->middleware('hasRole:admin,visitor')->group(function () {
        Route::get('/', [RoleController::class, 'index'])->name('index')->middleware('hasPermission:role.view');
        Route::get('/create', [RoleController::class, 'create'])->name('create')->middleware('hasPermission:role.create');
        Route::post('/create', [RoleController::class, 'store'])->name('store')->middleware('hasPermission:role.create');
        Route::get('/edit/{id}', [RoleController::class, 'edit'])->name('edit')->middleware('hasPermission:role.update');
        Route::put('/edit/{id}', [RoleController::class, 'update'])->name('update')->middleware('hasPermission:role.update');
        Route::delete('/delete/{id}', [RoleController::class, 'destroy'])->name('destroy')->middleware('hasPermission:role.delete');
    });

    //----------------------------------------------Permission----------------------------------//
    Route::prefix('/permission')->name('permissions.')->middleware('hasRole:admin,visitor')->group(function () {
        Route::get('/', [PermissionController::class, 'index'])->name('index')->middleware('hasPermission:permission.view');
        Route::get('/create', [PermissionController::class, 'create'])->name('create')->middleware('hasPermission:permission.create');
        Route::post('/create', [PermissionController::class, 'store'])->name('store')->middleware('hasPermission:permission.create');
        Route::get('/edit/{id}', [PermissionController::class, 'edit'])->name('edit')->middleware('hasPermission:permission.update');
        Route::put('/edit/{id}', [PermissionController::class, 'update'])->name('update')->middleware('hasPermission:permission.update');
        Route::delete('/delete/{id}', [PermissionController::class, 'destroy'])->name('destroy')->middleware('hasPermission:permission.delete');
    });

    //---------------------------------------------Category---------------------------------------//
    Route::prefix('/category')->name('categories.')->middleware('hasRole:admin,visitor')->group(function () {
        Route::get('/', [CategoryController::class, 'index'])->name('index')->middleware('hasPermission:category.view');
        Route::get('/create', [CategoryController::class, 'create'])->name('create')->middleware('hasPermission:category.create');
        Route::post('/create', [CategoryController::class, 'store'])->name('store')->middleware('hasPermission:category.create');
        Route::get('/edit/{id}', [CategoryController::class, 'edit'])->name('edit')->middleware('hasPermission:category.update');
        Route::put('/edit/{id}', [CategoryController::class, 'update'])->name('update')->middleware('hasPermission:category.update');
        Route::delete('/delete/{id}', [CategoryController::class, 'destroy'])->name('destroy')->middleware('hasPermission:category.delete');
    });

    //---------------------------------------------Product-----------------------------------------//
    Route::prefix('/product')->name('products.')->middleware('hasRole:admin,visitor')->group(function () {
        Route::get('/', [ProductController::class, 'index'])->name('index')->middleware('hasPermission:product.view');
        Route::post('/store', [ProductController::class, 'store'])->name('store')->middleware('hasPermission:product.create');
        Route::get('/edit/{id}', [ProductController::class, 'edit'])->name('edit')->middleware('hasPermission:product.update');
        Route::post('/update', [ProductController::class, 'update'])->name('update')->middleware('hasPermission:product.update');
        Route::delete('/delete/{id}', [ProductController::class, 'destroy'])->name('destroy')->middleware('hasPermission:product.delete');
    });
});

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    use HasFactory;

    protected $table = 'categories';
    public $timestamps = false;
    protected $fillable = [
        'name'
    ];

    public function hasManyProduct(){
        return $this->hasMany(Product::class, 'category_id', 'id');
    }

    public function scopeSearchCategory($query)
    {
        if(!empty(request()->category_id)){
            $query->where('id', request()->category_id);
        }
        return $query;
    }
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CategoryRequest;
use App\Services\CategoryService;
use Illuminate\Http\Request;

class CategoryController extends Controller
{
    protected $categoryService;

    public function __construct(CategoryService $categoryService)
    {
        $this->categoryService = $categoryService;
    }

    public function index()
    {
        $categories = $this->categoryService->getAll();
        return view('categories.index', compact('categories'));
    }

    public function create()
    {
        return view('categories.create');
    }

    public function store(CategoryRequest $request)
    {
        $this->categoryService->store($request);
        return redirect()->route('categories.index');
    }

    public function edit($id)
    {
        $category = $this->categoryService->getItemById($id);
        return view('categories.update', compact('category'));
    }

    public function update(Request $request, $id)
    {
        $this->categoryService->update($request, $id);
        return redirect()->route('categories.index');
    }

    public function destroy($id)
    {
        $this->categoryService->delete($id);
        return redirect()->route('categories.index');
    }
}

resources/views/categories/create.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">Create Category</div>

                    <div class="card-body">
                        <form action="{{route('categories.store')}}" method="POST">
                            @csrf
                            <div class="mb-3">
                                <div class="mb-3">
                                    <input type="text" class="form-control" name="name" placeholder="Name...">
                                    @error('name')
                                    <span id="name-error" class="text-danger" style="display: block">
                                        {{$message}}
                                    </span>
                                    @enderror
                                </div>
                                <input type="submit" class="btn btn-success" value="Submit">
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/categories/index.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">All Categories</div>
                    <div class="card-body mb-3">
                        @hasPermission(['category.create'])
                            <div class="mb-3">
                                <a href="{{route('categories.create')}}" class="btn btn-primary">Create New Category</a>
                            </div>
                        @endhasPermission
                        <table class="table table-bordered">
                            <thead>
                            <tr>
                                <th scope="col">#</th>
                                <th scope="col">Name</th>
                                @hasPermission(['category.update','category.delete'])
                                <th scope="col">Actions</th>
                                @endhasPermission
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($categories as $key => $category)
                                <tr>
                                    <th scope="row">{{++$key}}</th>
                                    <td>{{$category->name}}</td>
                                    <td>
                                        @hasPermission(['category.update'])
                                            <a href="{{route('categories.edit', $category->id)}}">
                                                <button type="button" class="btn btn-warning float-left">Edit</button>
                                            </a>
                                        @endhasPermission
                                        @hasPermission(['category.delete'])
                                            <form action="{{route('categories.destroy', $category->id)}}" method="POST"
                                                  class="float-left">
                                                @csrf
                                                @method('DELETE')
                                                <button type="submit" class="btn btn-danger">Delete</button>
                                            </form>
                                        @endhasPermission
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/categories/update.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">Create Category</div>

                    <div class="card-body">
                        <form action="{{route('categories.edit', $category->id)}}" method="POST">
                            @csrf
                            @method('PUT')
                            <div class="mb-3">
                                <div class="mb-3">
                                    <input type="text" class="form-control" name="name" placeholder="Name..." value="{{$category->name}}">
                                    @error('name')
                                    <span id="name-error" class="text-danger" style="display: block">
                                        {{$message}}
                                    </span>
                                    @enderror
                                </div>
                                <input type="submit" class="btn btn-success" value="Submit">
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection