routes/web.php
<?php

use App\Http\Controllers\CategoryController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\PermissionController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::resource('/admin/users', UserController::class)
    ->middleware('can:manage-users');

Route::prefix('admin')->middleware('auth')->group(function () {
    //--------------------------------------------Role------------------------------------------//
    Route::prefix('/role')->name('roles.')->middleware('hasRole:admin,visitor')->group(function () {
        Route::get('/', [RoleController::class, 'index'])->name('index')->middleware('hasPermission:role.view');
        Route::get('/create', [RoleController::class, 'create'])->name('create')->middleware('hasPermission:role.create');
        Route::post('/create', [RoleController::class, 'store'])->name('store')->middleware('hasPermission:role.create');
        Route::get('/edit/{id}', [RoleController::class, 'edit'])->name('edit')->middleware('hasPermission:role.update');
        Route::put('/edit/{id}', [RoleController::class, 'update'])->name('update')->middleware('hasPermission:role.update');
        Route::delete('/delete/{id}', [RoleController::class, 'destroy'])->name('destroy')->middleware('hasPermission:role.delete');
    });

    //----------------------------------------------Permission----------------------------------//
    Route::prefix('/permission')->name('permissions.')->middleware('hasRole:admin,visitor')->group(function () {
        Route::get('/', [PermissionController::class, 'index'])->name('index')->middleware('hasPermission:permission.view');
        Route::get('/create', [PermissionController::class, 'create'])->name('create')->middleware('hasPermission:permission.create');
        Route::post('/create', [PermissionController::class, 'store'])->name('store')->middleware('hasPermission:permission.create');
        Route::get('/edit/{id}', [PermissionController::class, 'edit'])->name('edit')->middleware('hasPermission:permission.update');
        Route::put('/edit/{id}', [PermissionController::class, 'update'])->name('update')->middleware('hasPermission:permission.update');
        Route::delete('/delete/{id}', [PermissionController::class, 'destroy'])->name('destroy')->middleware('hasPermission:permission.delete');
    });

    //---------------------------------------------Category---------------------------------------//
    Route::prefix('/category')->name('categories.')->middleware('hasRole:admin,visitor')->group(function () {
        Route::get('/', [CategoryController::class, 'index'])->name('index')->middleware('hasPermission:category.view');
        Route::get('/create', [CategoryController::class, 'create'])->name('create')->middleware('hasPermission:category.create');
        Route::post('/create', [CategoryController::class, 'store'])->name('store')->middleware('hasPermission:category.create');
        Route::get('/edit/{id}', [CategoryController::class, 'edit'])->name('edit')->middleware('hasPermission:category.update');
        Route::put('/edit/{id}', [CategoryController::class, 'update'])->name('update')->middleware('hasPermission:category.update');
        Route::delete('/delete/{id}', [CategoryController::class, 'destroy'])->name('destroy')->middleware('hasPermission:category.delete');
    });

    //---------------------------------------------Product-----------------------------------------//
    Route::prefix('/product')->name('products.')->middleware('hasRole:admin,visitor')->group(function () {
        Route::get('/', [ProductController::class, 'index'])->name('index')->middleware('hasPermission:product.view');
        Route::post('/store', [ProductController::class, 'store'])->name('store')->middleware('hasPermission:product.create');
        Route::get('/edit/{id}', [ProductController::class, 'edit'])->name('edit')->middleware('hasPermission:product.update');
        Route::post('/update', [ProductController::class, 'update'])->name('update')->middleware('hasPermission:product.update');
        Route::delete('/delete/{id}', [ProductController::class, 'destroy'])->name('destroy')->middleware('hasPermission:product.delete');
    });
});

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    use HasFactory;

    protected $table = 'products';
    public $timestamps = false;
    protected $fillable = [
        'name',
        'price',
        'description',
        'thumbnail',
        'category_id'
    ];

    public function categories()
    {
        return $this->belongsTo(Category::class, 'category_id', 'id');
    }

    public function scopeSearchProductName($query)
    {
        if(!empty(request()->key)){
          $query->where('name', 'like', '%' . request()->key . '%');
        }
        return $query;
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\ProductRequest;
use App\Services\CategoryService;
use App\Services\ProductService;

class ProductController extends Controller
{
    protected $productService;
    protected $categoryService;

    public function __construct(ProductService $productService, CategoryService $categoryService)
    {
        $this->productService = $productService;
        $this->categoryService = $categoryService;
    }

    public function index()
    {
        $products = $this->productService->search();
        $categories = $this->categoryService->getAll();
        return view('products.index', compact('products', 'categories'));
    }

    public function store(ProductRequest $request)
    {
        $product = $this->productService->store($request);
        return response()->json([
            'status_code' => 200,
            'product' => $product,
            'message' => "Create new product success!"
        ]);
    }

    public function edit($id)
    {
        $product = $this->productService->getItemById($id);
        $categories = $this->categoryService->getAll();
        return response()->json([
            'status_code' => 200,
            'product' => $product,
            'categories' => $categories
        ]);
    }

    public function update(ProductRequest $request)
    {
        $product = $this->productService->update($request);
        return response()->json([
            'status_code' => 200,
            'product' => $product,
            'message' => "Update product success!"
        ]);
    }

    public function destroy($id)
    {
        $this->productService->delete($id);
        return response()->json([
            'status_code' => 200,
        ]);
    }
}

resources/views/products/create.blade.php
<!-- Modal -->
<div class="modal fade" id="create-product" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
     aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Create Product</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form id="form-create-product" data-url="{{ route('products.store') }}" method="POST" role="form"
                  enctype="multipart/form-data">
                @csrf
                <div class="card-body">
                    <div class="mb-3">
                        <input type="text" id="name" class="form-control" name="name" placeholder="Name..."/>
                        <p class="text-danger" id="name-error"></p>
                    </div>
                    <div class="mb-3">
                        <input type="number" id="price" step="any" class="form-control" name="price"
                               placeholder="Price..."/>
                        <p class="text-danger" id="price-error"></p>
                    </div>
                    <div class="mb-3">
                        <textarea class="form-control" id="description" rows="3" name="description"
                                  placeholder="Descriptions...">
                        </textarea>
                        <p class="text-danger" id="description-error"></p>
                    </div>
                    <div class="mb-3">
                        <label class="form-label">Category</label>
                        <select class="form-select form-control" id="category-id" name="category_id">
                            @foreach ($categories as $category)
                                <option value="{{ $category->id }}">{{ $category->name }}</option>
                            @endforeach
                        </select>
                    </div>
                    <div class="mb-3">
                        <label class="form-label">Image product</label>
                        <input class="form-control" id="file-thumbnail" type="file" name="fileThumbnail"/>
                        <p class="text-danger" id="fileThumbnail-error"></p>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

resources/views/products/index.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">All Products</div>
                    <div class="card-body">
                        @hasPermission(['product.create'])
                        <div class="mb-3">
                            <button type="button" class="btn btn-primary" data-toggle="modal"
                                    data-target="#create-product">
                                Create New Product
                            </button>
                        </div>
                        @endhasPermission
                        <div class="mb-3">
                            <form action="{{ route('products.index') }}" method="GET" class="d-flex">
                                <input type="text" class="form-control" name="key" value="{{request('key')}}">
                                <select name="category_id" class="col-md-3 form-control">
                                    <option value="0">Select category</option>
                                    @foreach ($categories as $category)
                                        <option
                                            value="{{ $category->id }}" {{ request('category_id') == $category->id ? "selected":"" }}>{{ $category->name }}
                                        </option>
                                    @endforeach
                                </select>
                                <button class="btn btn-primary" type="submit">Search</button>
                            </form>
                        </div>
                        <div id="table-list">
                            <table class="table table-bordered">
                                <thead>
                                <tr>
                                    <th scope="col">#</th>
                                    <th scope="col">Name</th>
                                    <th scope="col">Price</th>
                                    <th scope="col">Description</th>
                                    <th scope="col">Image</th>
                                    <th scope="col">Category</th>
                                    @hasPermission(['product.update','product.delete'])
                                    <th scope="col">Actions</th>
                                    @endhasPermission
                                </tr>
                                </thead>
                                <tbody>
                                @foreach($products as $key => $product)
                                    <tr>
                                        <th scope="row">{{++$key}}</th>
                                        <td>{{$product->name}}</td>
                                        <td>{{number_format($product->price)}} VND</td>
                                        <td>{{$product->description}}</td>
                                        <td>
                                            <img class="img-responsive img-rounded"
                                                 style="max-height: 100px; max-width: 100px;"
                                                 src="{{url('uploads/products/'.$product->thumbnail)}}"
                                                 alt="{{$product->name}}">
                                        </td>
                                        <td>{{$product->categories->name}}</td>
                                        @hasPermission(['product.update','product.delete'])
                                        <td>
                                            @hasPermission(['product.update'])
                                            <button data-url="{{route('products.edit', $product->id)}}" type="button"
                                                    class="btn btn-warning btn-edit">
                                                Edit
                                            </button>
                                            @endhasPermission
                                            @hasPermission(['product.delete'])
                                            <button data-url="{{route('products.destroy', $product->id)}}" type="button"
                                                    class="btn btn-danger btn-delete">
                                                Delete
                                            </button>
                                            @endhasPermission
                                        </td>
                                        @endhasPermission
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                        </div>
                        {{$products->links()}}
                    </div>
                </div>
                {{-- Modal for create product --}}
                @include('products.create')
                {{-- Modal for update product --}}
                @include('products.update')
            </div>
        </div>
    </div>
@endsection
@section('script')
    <script defer src="{{ asset('admin/assets/js/product.js') }}" type="text/javascript"></script>
@endsection

resources/views/products/update.blade.php
<!-- Modal -->
<div class="modal fade" id="update-product" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
     aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Update Product</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form id="form-update-product" data-url="{{ route('products.update') }}" method="POST"
                  enctype="multipart/form-data">
                @csrf
                <input type="hidden" name="id" id="id-product-edit">
                <div class="card-body">
                    <div class="mb-3">
                        <input type="text" id="name-edit" class="form-control" name="name"
                               placeholder="Name..."/>
                        <p class="text-danger" id="name-update-error"></p>
                    </div>
                    <div class="mb-3">
                        <input type="number" id="price-edit" class="form-control" name="price"
                               placeholder="Price..."/>
                        <p class="text-danger" id="price-update-error"></p>
                    </div>
                    <div class="mb-3">
                        <textarea id="description-edit" class="form-control" rows="3" name="description"
                                  placeholder="Descriptions...">
                        </textarea>
                        <p class="text-danger" id="description-update-error"></p>
                    </div>
                    <div class="mb-3">
                        <label class="form-label">Category</label>
                        <select id="category-id-edit" class="form-select form-control" name="category_id">
                            @foreach ($categories as $category)
                                <option value="{{ $category->id }}">{{ $category->name }}
                                </option>
                            @endforeach
                        </select>
                    </div>
                    <div class="mb-3">
                        <label class="form-label">Image product</label>
                        <input id="file-thumbnail-edit" class="form-control" type="file" name="fileThumbnail"/>
                        <p class="text-danger" id="fileThumbnail-update-error"></p>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-primary">Update</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>