routes/web.php
<?php

use App\Http\Controllers\CategoryController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\PermissionController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::resource('/admin/users', UserController::class)
    ->middleware('can:manage-users');

Route::prefix('admin')->middleware('auth')->group(function () {
    //--------------------------------------------Role------------------------------------------//
    Route::prefix('/role')->name('roles.')->middleware('hasRole:admin,visitor')->group(function () {
        Route::get('/', [RoleController::class, 'index'])->name('index')->middleware('hasPermission:role.view');
        Route::get('/create', [RoleController::class, 'create'])->name('create')->middleware('hasPermission:role.create');
        Route::post('/create', [RoleController::class, 'store'])->name('store')->middleware('hasPermission:role.create');
        Route::get('/edit/{id}', [RoleController::class, 'edit'])->name('edit')->middleware('hasPermission:role.update');
        Route::put('/edit/{id}', [RoleController::class, 'update'])->name('update')->middleware('hasPermission:role.update');
        Route::delete('/delete/{id}', [RoleController::class, 'destroy'])->name('destroy')->middleware('hasPermission:role.delete');
    });

    //----------------------------------------------Permission----------------------------------//
    Route::prefix('/permission')->name('permissions.')->middleware('hasRole:admin,visitor')->group(function () {
        Route::get('/', [PermissionController::class, 'index'])->name('index')->middleware('hasPermission:permission.view');
        Route::get('/create', [PermissionController::class, 'create'])->name('create')->middleware('hasPermission:permission.create');
        Route::post('/create', [PermissionController::class, 'store'])->name('store')->middleware('hasPermission:permission.create');
        Route::get('/edit/{id}', [PermissionController::class, 'edit'])->name('edit')->middleware('hasPermission:permission.update');
        Route::put('/edit/{id}', [PermissionController::class, 'update'])->name('update')->middleware('hasPermission:permission.update');
        Route::delete('/delete/{id}', [PermissionController::class, 'destroy'])->name('destroy')->middleware('hasPermission:permission.delete');
    });

    //---------------------------------------------Category---------------------------------------//
    Route::prefix('/category')->name('categories.')->middleware('hasRole:admin,visitor')->group(function () {
        Route::get('/', [CategoryController::class, 'index'])->name('index')->middleware('hasPermission:category.view');
        Route::get('/create', [CategoryController::class, 'create'])->name('create')->middleware('hasPermission:category.create');
        Route::post('/create', [CategoryController::class, 'store'])->name('store')->middleware('hasPermission:category.create');
        Route::get('/edit/{id}', [CategoryController::class, 'edit'])->name('edit')->middleware('hasPermission:category.update');
        Route::put('/edit/{id}', [CategoryController::class, 'update'])->name('update')->middleware('hasPermission:category.update');
        Route::delete('/delete/{id}', [CategoryController::class, 'destroy'])->name('destroy')->middleware('hasPermission:category.delete');
    });

    //---------------------------------------------Product-----------------------------------------//
    Route::prefix('/product')->name('products.')->middleware('hasRole:admin,visitor')->group(function () {
        Route::get('/', [ProductController::class, 'index'])->name('index')->middleware('hasPermission:product.view');
        Route::post('/store', [ProductController::class, 'store'])->name('store')->middleware('hasPermission:product.create');
        Route::get('/edit/{id}', [ProductController::class, 'edit'])->name('edit')->middleware('hasPermission:product.update');
        Route::post('/update', [ProductController::class, 'update'])->name('update')->middleware('hasPermission:product.update');
        Route::delete('/delete/{id}', [ProductController::class, 'destroy'])->name('destroy')->middleware('hasPermission:product.delete');
    });
});

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>{{ config('app.name', 'Laravel') }}</title>
    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">
    <!-- Styles -->
    <link href="{{ asset('admin/assets/vendor/fontawesome-free/css/all.min.css') }}" rel="stylesheet" type="text/css">
    <link href="{{ asset('admin/assets/css/sb-admin-2.min.css') }}" rel="stylesheet">
</head>
<body>
<div id="app">
    <main>
        <div id="wrapper">
            <!-- Sidebar -->
            <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">
                <!-- Sidebar - Brand -->
                <a class="sidebar-brand d-flex align-items-center justify-content-center" href="#">
                    <div class="sidebar-brand-icon rotate-n-15">
                        <i class="fas fa-laugh-wink"></i>
                    </div>
                    <div class="sidebar-brand-text mx-3">SB Admin <sup>2</sup></div>
                </a>
                <!-- Divider -->
                <hr class="sidebar-divider my-0">
                <!-- Nav Item - Dashboard -->
                <li class="nav-item">
                    <a class="nav-link" href="#">
                        <i class="fas fa-fw fa-tachometer-alt"></i>
                        <span>Dashboard</span></a>
                </li>
                <!-- Divider -->
                <hr class="sidebar-divider">
                <!-- Nav Item - Tables -->
                @can('manage-users')
                    <li class="nav-item active">
                        <a class="nav-link" href="{{route('users.index')}}">
                            <i class="fas fa-fw fa-table"></i>
                            <span>User Managemnet</span></a>
                    </li>
                @endcan
                <li class="nav-item active">
                    <a class="nav-link" href="{{route('roles.index')}}">
                        <i class="fas fa-fw fa-table"></i>
                        <span>Role Managemnet</span></a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{{route('permissions.index')}}">
                        <i class="fas fa-fw fa-table"></i>
                        <span>Permisson Managemnet</span></a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{{route('categories.index')}}">
                        <i class="fas fa-fw fa-table"></i>
                        <span>Category Managemnet</span></a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{{route('products.index')}}">
                        <i class="fas fa-fw fa-table"></i>
                        <span> Product Managemnet</span></a>
                </li>
                <hr class="sidebar-divider">
                <!-- Sidebar Toggler (Sidebar) -->
                <div class="text-center d-none d-md-inline">
                    <button class="rounded-circle border-0" id="sidebarToggle"></button>
                </div>
            </ul>
            <!-- End of Sidebar -->
            <!-- Content Wrapper -->
            <div id="content-wrapper" class="d-flex flex-column">
                <!-- Main Content -->
                <div id="content">
                    <!-- Topbar -->
                    <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">
                        <!-- Sidebar Toggle (Topbar) -->
                        <form class="form-inline">
                            <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                                <i class="fa fa-bars"></i>
                            </button>
                        </form>
                        <!-- Topbar Navbar -->
                        <ul class="navbar-nav ml-auto">
                            <ul class="navbar-nav ml-auto">
                                <!-- Authentication Links -->
                                @guest
                                    @if (Route::has('login'))
                                        <li class="nav-item">
                                            <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                                        </li>
                                    @endif

                                    @if (Route::has('register'))
                                        <li class="nav-item">
                                            <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                        </li>
                                    @endif
                                @else
                                    <li class="nav-item dropdown">
                                        <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button"
                                           data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                            {{ Auth::user()->name }}
                                        </a>

                                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                            <a class="dropdown-item" href="{{ route('logout') }}"
                                               onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                                {{ __('Logout') }}
                                            </a>

                                            <form id="logout-form" action="{{ route('logout') }}" method="POST"
                                                  class="d-none">
                                                @csrf
                                            </form>
                                        </div>
                                    </li>
                                @endguest
                            </ul>
                        </ul>
                    </nav>
                    <!-- End of Topbar -->

                    <!-- Begin Page Content -->
                    <div class="container-fluid">
                        @yield('content')
                    </div>
                    <!-- /.container-fluid -->
                </div>
                <!-- End of Main Content -->
                <footer class="sticky-footer bg-white">
                    <div class="container my-auto">
                        <div class="copyright text-center my-auto">
                            <span>Copyright &copy; Your Website 2020</span>
                        </div>
                    </div>
                </footer>
            </div>
            <!-- End of Content Wrapper -->
        </div>
    </main>
    <script src="{{asset('admin/assets/vendor/jquery/jquery.min.js')}}"></script>
    <script src="{{asset('admin/assets/vendor/bootstrap/js/bootstrap.bundle.min.js')}}"></script>
    <script src="{{ asset('admin/assets/vendor/jquery-easing/jquery.easing.min.js') }}"></script>
    <script src="{{ asset('admin/assets/js/sb-admin-2.min.js') }}"></script>
    @yield('script')
</div>
</body>
</html>