routes/web.php
<?php

use App\Http\Controllers\CategoryController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\PermissionController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::resource('/admin/users', UserController::class)
    ->middleware('can:manage-users');

Route::prefix('admin')->middleware('auth')->group(function () {
    //--------------------------------------------Role------------------------------------------//
    Route::prefix('/role')->name('roles.')->middleware('hasRole:admin,visitor')->group(function () {
        Route::get('/', [RoleController::class, 'index'])->name('index')->middleware('hasPermission:role.view');
        Route::get('/create', [RoleController::class, 'create'])->name('create')->middleware('hasPermission:role.create');
        Route::post('/create', [RoleController::class, 'store'])->name('store')->middleware('hasPermission:role.create');
        Route::get('/edit/{id}', [RoleController::class, 'edit'])->name('edit')->middleware('hasPermission:role.update');
        Route::put('/edit/{id}', [RoleController::class, 'update'])->name('update')->middleware('hasPermission:role.update');
        Route::delete('/delete/{id}', [RoleController::class, 'destroy'])->name('destroy')->middleware('hasPermission:role.delete');
    });

    //----------------------------------------------Permission----------------------------------//
    Route::prefix('/permission')->name('permissions.')->middleware('hasRole:admin,visitor')->group(function () {
        Route::get('/', [PermissionController::class, 'index'])->name('index')->middleware('hasPermission:permission.view');
        Route::get('/create', [PermissionController::class, 'create'])->name('create')->middleware('hasPermission:permission.create');
        Route::post('/create', [PermissionController::class, 'store'])->name('store')->middleware('hasPermission:permission.create');
        Route::get('/edit/{id}', [PermissionController::class, 'edit'])->name('edit')->middleware('hasPermission:permission.update');
        Route::put('/edit/{id}', [PermissionController::class, 'update'])->name('update')->middleware('hasPermission:permission.update');
        Route::delete('/delete/{id}', [PermissionController::class, 'destroy'])->name('destroy')->middleware('hasPermission:permission.delete');
    });

    //---------------------------------------------Category---------------------------------------//
    Route::prefix('/category')->name('categories.')->middleware('hasRole:admin,visitor')->group(function () {
        Route::get('/', [CategoryController::class, 'index'])->name('index')->middleware('hasPermission:category.view');
        Route::get('/create', [CategoryController::class, 'create'])->name('create')->middleware('hasPermission:category.create');
        Route::post('/create', [CategoryController::class, 'store'])->name('store')->middleware('hasPermission:category.create');
        Route::get('/edit/{id}', [CategoryController::class, 'edit'])->name('edit')->middleware('hasPermission:category.update');
        Route::put('/edit/{id}', [CategoryController::class, 'update'])->name('update')->middleware('hasPermission:category.update');
        Route::delete('/delete/{id}', [CategoryController::class, 'destroy'])->name('destroy')->middleware('hasPermission:category.delete');
    });

    //---------------------------------------------Product-----------------------------------------//
    Route::prefix('/product')->name('products.')->middleware('hasRole:admin,visitor')->group(function () {
        Route::get('/', [ProductController::class, 'index'])->name('index')->middleware('hasPermission:product.view');
        Route::post('/store', [ProductController::class, 'store'])->name('store')->middleware('hasPermission:product.create');
        Route::get('/edit/{id}', [ProductController::class, 'edit'])->name('edit')->middleware('hasPermission:product.update');
        Route::post('/update', [ProductController::class, 'update'])->name('update')->middleware('hasPermission:product.update');
        Route::delete('/delete/{id}', [ProductController::class, 'destroy'])->name('destroy')->middleware('hasPermission:product.delete');
    });
});

app/Models/Role.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Role extends Model
{
    use HasFactory;

    protected $table = 'roles';
    public $timestamps = false;
    protected $fillable = [
        'name'
    ];

    public function users(){
        return $this->belongsToMany(User::class,'user_role','role_id','user_id');
    }

    public function permissions(){
        return $this->belongsToMany(Permission::class,'role_permission','role_id','permission_id');
    }

    public function hasPermission($permissions)
    {
        foreach($permissions as $permission)
        {
            if($this->permissions->contains('name', $permission)){
                return true;
            }
        }
        return false;
    }

}

app/Http/Controllers/RoleController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\RoleRequest;
use App\Services\PermissionService;
use App\Services\RoleService;

class RoleController extends Controller
{
    protected $roleService;
    protected $permissionService;

    public function __construct(RoleService $roleService, PermissionService $permissionService)
    {
        $this->roleService = $roleService;
        $this->permissionService = $permissionService;
    }

    public function index()
    {
        $roles = $this->roleService->getAll();
        return view('roles.index', compact('roles'));
    }

    public function create()
    {
        $permissions = $this->permissionService->getAll();
        return view('roles.create', compact('permissions'));
    }

    public function store(RoleRequest $request)
    {
        $this->roleService->store($request);
        return redirect()->route('roles.index');
    }

    public function edit($id)
    {
        $role = $this->roleService->getItemById($id);
        $permissions = $this->permissionService->getAll();
        return view('roles.update', compact('role', 'permissions'));
    }

    public function update(RoleRequest $request, $id)
    {
        $this->roleService->update($request, $id);
        return redirect()->route('roles.index');

    }

    public function destroy($id)
    {
        $this->roleService->delete($id);
        return redirect()->route('roles.index');
    }
}

resources/views/roles/create.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">Create Roles</div>
                    <div class="card-body">
                        <form action="{{route('roles.store')}}" method="POST">
                            @csrf
                            <div class="mb-3">
                                <input type="text" class="form-control" name="name" placeholder="Name...">
                                @error('name')
                                <span id="name-error" class="text-danger" style="display: block">
                                        {{$message}}
                                    </span>
                                @enderror
                            </div>
                            @foreach($permissions as $permission)
                                <div class="form-check">
                                    <input type="checkbox" name="permissions[]"
                                           value="{{$permission->id}}">
                                    <label for="">{{$permission->name}}</label>
                                </div>
                            @endforeach
                            <input type="submit" class="btn btn-success" value="Submit">
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/roles/index.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">All Roles</div>
                    <div class="card-body mb-3">
                        @hasRole(['admin'])
                        <div class="mb-3">
                            <a href="{{route('roles.create')}}" class="btn btn-primary">Create New Role</a>
                        </div>
                        @endhasRole
                        <table class="table table-bordered">
                            <thead>
                            <tr>
                                <th scope="col">#</th>
                                <th scope="col">Name</th>
                                @hasRole(['admin'])
                                <th scope="col">Actions</th>
                                @endhasRole
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($roles as $key => $role)
                                <tr>
                                    <th scope="row">{{++$key}}</th>
                                    <td>{{$role->name}}</td>
                                    @hasRole(['admin'])
                                    <td>
                                        <a href="{{route('roles.edit', $role->id)}}">
                                            <button type="button" class="btn btn-warning float-left">Edit</button>
                                        </a>
                                        <form action="{{route('roles.destroy', $role->id)}}" method="POST"
                                              class="float-left">
                                            @csrf
                                            @method('DELETE')
                                            <button type="submit" class="btn btn-danger">Delete</button>
                                        </form>
                                    </td>
                                    @endhasRole
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/roles/update.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">Edit Role</div>

                    <div class="card-body">
                        <form action="{{route('roles.update', $role->id)}}" method="POST">
                            @csrf
                            @method('PUT')
                            <div class="mb-3">
                                <input type="text" class="form-control" name="name" placeholder="Name..."
                                       value="{{$role->name}}">
                                @error('name')
                                <span id="name-error" class="text-danger" style="display: block">
                                        {{$message}}
                                    </span>
                                @enderror
                            </div>
                            @foreach($permissions as $permission)
                                <div class="form-check">
                                    <input type="checkbox" name="permissions[]" value="{{$permission->id}}"
                                           @if ($role->permissions->pluck('id')->contains($permission->id)) checked @endif>
                                    <label for="">{{$permission->name}}</label>
                                </div>
                            @endforeach
                            <button type="submit" class="btn btn-primary">
                                Update
                            </button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection